codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto
    changes:
      default:
        base: auto

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  backend:
    paths:
      - backend/src/
    carryforward: true
  frontend:
    paths:
      - frontend/src/
    carryforward: true

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/tests/**"
  - "**/__tests__/**"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/coverage/**"
  - "**/*.config.js"
  - "**/*.config.ts"
  - "**/vite.config.ts"
  - "**/vitest.config.ts"
  - "**/jest.config.js"
  - "**/eslint.config.js"
